routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Auth::routes();
Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::resource('requirement', 'RequirementController')->middleware('auth');

Route::get('/requirement/{id}', 'RequirementController@show')->middleware('auth');
Route::resource('requirementtype','RequirementTypeController')->middleware('auth');
Route::get('/requirements/json', 'RequirementController@json')->middleware('auth');

/** 
 *   AUTH PROTECTED ROUTES
 */
Route::group(['middleware' => ['auth']], function()
{
    Route::get('/', function () {
        return view('dashboard');
    });
    Route::get('/requirements/search', 'RequirementController@search')->name('requirement.search');    
});

/**
 *  RESOURCES
 */
Route::resource('requirement', 'RequirementController',
                ['only' => ['index', 'show']])->middleware('auth');

Route::resource('requirement', 'RequirementController',
    ['except' => ['create', 'store', 'update', 'destroy']])->middleware(['auth']);

    Route::get('requirement/types', 'RequirementTypeController@index')->name('types.all');

    Route::prefix('requirement')->name('requirement.')->group(function () {
        Route::get('{id}/types', 'RequirementController@types')->name('types');
        Route::get('{id}/quotes', 'RequirementController@quotes')->name('quotes');
       
    });

    Route::prefix('requirements')->name('requirements.')->group(function () {

        Route::get('open', 'RequirementController@index')->name('open')->middleware(['auth']);
        Route::get('recent', 'RequirementController@getRecent')->name('recent')->middleware(['auth']);
        Route::get('quotes', 'RequirementController@getRecievedQuotes')->name('quotes')->middleware(['auth']);
        Route::get('{requirement}/show/json', 'RequirementController@getJson')->name('get.json')->middleware(['auth']);
       
    });

    /**
     *  QUOTE ROUTES
     */

    Route::prefix('quote')->name('quote.')->group(function () {

        Route::post('delete/{id}', 'QuoteController@delete')->name('delete')->middleware(['auth']);
        Route::get('/{id}', 'QuoteController@quotes')->name('show')->middleware(['auth']);
        Route::post('/sync','QuoteOptionController@sync')->name('sync')->middleware(['auth']);
        Route::get('/{requirementId}/new', 'QuoteController@create')->name('create')->middleware(['auth']);
        Route::post('/{requirementId}/store', 'QuoteController@store')->name('store')->middleware(['auth']);
        Route::post('submit/{requirementId}', 'QuoteController@submit')->name('submit')->middleware(['auth']);
        

        /**
         *  QUOTE OPTIONS
         */
        Route::get('/{requirementId}/options', 'QuoteOptionController@listByRequirement')->name('options')->middleware(['auth']);
        Route::post('/{requirementId}/options/{optionId}/delete', 'QuoteOptionController@destroy')->name('option.delete')->middleware(['auth']);
        Route::post('options/store', 'QuoteOptionController@store')->name('store')->middleware(['auth']);
    });

        
    /**
     *  JSON ROUTE PREFIX
     */
    
        Route::prefix('json/')->name('requirement.')->group(function () {

            /**
             *  Quote options
             */
            Route::post('quoteoption/{requirementId}/store', 'QuoteOptionController@store')->middleware(['auth']);
            Route::delete('quoteoption/{quoteoption}', 'QuoteOptionController@destroy')->middleware(['auth']);
            Route::post('quoteoption/{quoteOption}/update', 'QuoteOptionController@update')->middleware(['auth']);
           // Route::post('quoteoption/update/{quoteoption}', 'QuoteOptionController@update')->name('quoteoption.update')->middleware(['auth']);
        
            /**
             * 
             *  Quotes
             */
            Route::get('/quote/{requirement}', 'QuoteController@getQuoteByRequirement')->middleware(['auth']);
        });
    
    Route::prefix('quotes')->name('quotes.')->group(function () {

        Route::get('review', 'QuoteController@review')->name('review')->middleware(['auth']);
        Route::get('staged', 'QuoteController@getStaged')->name('staged')->middleware(['auth']);
        Route::get('review/confirmation', 'QuoteController@getConfirmation')->name('confirmation')->middleware(['auth']);
        
    
    });
    

    /**
     *  USER ROUTES
     */

    Route::prefix('user')->name('user.')->group(function () {

        Route::get('quotes', 'UserController@getQuotes')->name('quotes')->middleware(['auth']);
        Route::get('aircraft', 'UserController@getAircraft')->name('aircraft')->middleware(['auth']);
        Route::get('subscriptions','UserController@getSubscriptions')->name('subscriptions')->middleware(['auth']);
        Route::get('profile','UserController@getProfile')->name('profile')->middleware(['auth']);
        Route::get('dashboard', 'UserController@dashboard')->name('dashboard')->middleware(['auth']);
    });

resources/views/partials/_footer.blade.php
<!-- Scripts -->

{{--  CDNs  --}}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

  <script src="{{ asset('js/app.js') }}"></script>
  @yield('footer-scripts')

<footer class="app-footer" style="margin-top:30px;">
  <div>
    <span>&copy; <?php echo date("Y");?> JetBid LLC</span>
  </div>
  <div class="ml-auto">
    <span>JetBid is a </span>
    <a href="https://flightmotionav.com">Flight Motion</a> company
  </div>
</footer>

resources/views/partials/_multilevelnode.blade.php
<li class=" ">
    <a href="#multilevel" title="Multilevel" data-toggle="collapse">
       <em class="fa fa-folder-open-o"></em>
       <span>Multilevel</span>
    </a>
    <ul class="sidebar-nav sidebar-subnav collapse" id="multilevel">
       <li class="sidebar-subnav-header">Multilevel</li>
       <li class=" ">
          <a href="#level1" title="Level 1" data-toggle="collapse">
             <span>Level 1</span>
          </a>
          <ul class="sidebar-nav sidebar-subnav collapse" id="level1">
             <li class="sidebar-subnav-header">Level 1</li>
             <li class=" ">
                <a href="multilevel-1.html" title="Level1 Item">
                   <span>Level1 Item</span>
                </a>
             </li>
             <li class=" ">
                <a href="#level2" title="Level 2" data-toggle="collapse">
                   <span>Level 2</span>
                </a>
                <ul class="sidebar-nav sidebar-subnav collapse" id="level2">
                   <li class="sidebar-subnav-header">Level 2</li>
                   <li class=" ">
                      <a href="#level3" title="Level 3" data-toggle="collapse">
                         <span>Level 3</span>
                      </a>
                      <ul class="sidebar-nav sidebar-subnav collapse" id="level3">
                         <li class="sidebar-subnav-header">Level 3</li>
                         <li class=" ">
                            <a href="multilevel-3.html" title="Level3 Item">
                               <span>Level3 Item</span>
                            </a>
                         </li>
                      </ul>
                   </li>
                </ul>
             </li>
          </ul>
       </li>
    </ul>
 </li>

resources/views/partials/_sidenav.blade.php
<div class="sidebar">
        <nav class="sidebar-nav">
          <ul class="nav">

    {{--  REQUIREMENTS  --}}

            <li class="nav-title">Requirements</li>
            <li class="nav-item">
                    <a class="nav-link" href="#">
                            <i class="nav-icon fas fa-clock"></i>
                        Recent
                        <span class="badge badge-primary">4</span>
                    </a>
            </li>

            <li class="nav-item">
                <a class="nav-link
                <?php if( url()->current() == route('requirements.open') ){
                        echo ' nav-link-primary';
                    }?>
                " href="{{ route('requirements.open') }}">
                        <i class="nav-icon fas fa-door-open"></i>
                    Open
                    
                </a>
            </li>
            
            {{--  IF AIRCRAFT APPROVED  --}}

            @if(Auth::user()->isAircraftApproved() )
            <li class="nav-item">
                    <a class="nav-link 
                    <?php

                    if( url()->current() == route('requirements.quotes') ){
                        echo ' nav-link-primary';
                    }?>" href="{!! route('requirements.quotes') !!}">
                            <i class="nav-icon fas fa-inbox"></i>
                        Inbox
                    </a>
                </li>
            <li class="nav-item">
                    <a class="nav-link" href="#">
                            <i class="nav-icon fas fa-plus-square"></i>
                        New Requirement
                    </a>
                </li>
                @endif

            <li class="nav-item">
                    <a class="nav-link" href="#">
                            <i class="nav-icon fas  fa-search"></i>
                        Advanced Search
                     
                        
                    </a>
                </li>
                
        {{--  YOUR QUOTES  --}}

        @if( Auth::user()->membershipIsActive() )
                <li class="nav-title ">Quotes</li>
                <li class="nav-item">
                        <a class="nav-link" href="#">
                                <i class="nav-icon fas fa-trophy"></i>
                            Approved
                            <span class="badge badge-success">3</span>
                        </a>
                    </li>

                    <li class="nav-item">
                            <a class="nav-link" href="#">
                                    <i class="nav-icon fas fa-share-square"></i>
                                Submitted
                                <span class="badge badge-default">16</span>
                            </a>
                    </li>

                    <li class="nav-item">
                            <a class="nav-link" href="#">
                                    <i class="nav-icon fas fa-door-closed"></i>
                                Closed
                                
                            </a>
                    </li>


                    <li class="nav-item">
                            <a class="nav-link" href="#">
                                    <i class="nav-icon fas fa-cloud-download-alt"></i>
                                Export
                               
                            </a>
                    </li>
        @endif


        {{--  YOUR AIRCAFT  --}}

                @if( Auth::user()->membershipIsActive() )
                <li class="nav-title ">Fleet</li>
                <li class="nav-item">
                        <a class="nav-link" href="#">
                                <i class="nav-icon fas fa-plane"></i>
                            Your Aircraft
                            <span class="badge badge-success">3</span>
                        </a>
                    </li>

                    <li class="nav-item">
                            <a class="nav-link" href="#">
                                    <i class="nav-icon fas fa-plus-square"></i>
                                Add Aircraft
                            </a>
                        </li>
        @endif
          </ul>
        </nav>
        <button class="sidebar-minimizer brand-minimizer" type="button"></button>
</div>

resources/views/partials/_topnav.blade.php
<header class="app-header navbar">
                <button class="navbar-toggler sidebar-toggler d-lg-none mr-auto" type="button" data-toggle="sidebar-show">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand" href="#">
                 
                  <img class="navbar-brand-full" src="{!! url('/') !!}/images/jetbid_logo.svg" width="120" alt="App Logo">
                  <img class="navbar-brand-minimized" src="{!! url('/') !!}/images/jetbid_logo.svg" width="60" alt="App Logo">

                </a>
                <button class="navbar-toggler sidebar-toggler d-md-down-none" type="button" data-toggle="sidebar-lg-show">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <ul class="nav navbar-nav d-md-down-none">
                  <li class="nav-item px-3">
                    <a class="nav-link" href="{{ route('user.dashboard') }}">Dashboard</a>
                  </li>
                  <li class="nav-item px-3">
                    <a class="nav-link" href="#">Users</a>
                  </li>
                  <li class="nav-item px-3">
                    <a class="nav-link" href="#">Settings</a>
                  </li>
                </ul>
                <ul class="nav navbar-nav ml-auto">
                  <li class="nav-item d-md-down-none">
                    <a class="nav-link" href="#">
                                <i class="fas fa-bell"></i>
                      <span class="badge badge-pill badge-danger">5</span>
                    </a>
                  </li>
                  <li class="nav-item d-md-down-none">
                    <a class="nav-link" href="#">
                      <i class="icon-list"></i>
                    </a>
                  </li>
                  <li class="nav-item d-md-down-none">
                    <a class="nav-link" href="#">
                      <i class="icon-location-pin"></i>
                    </a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-tachometer-alt"></i> Account
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                      <div class="dropdown-header text-center">
                        <strong>Account</strong>
                      </div>
                      <a class="dropdown-item" href="#">
                        <i class="fa fa-bell-o"></i> Updates
                        <span class="badge badge-info">42</span>
                      </a>
                      <a class="dropdown-item" href="#">
                        <i class="fa fa-envelope-o"></i> Messages
                        <span class="badge badge-success">42</span>
                      </a>
                      <a class="dropdown-item" href="#">
                        <i class="fa fa-tasks"></i> Tasks
                        <span class="badge badge-danger">42</span>
                      </a>
                      <a class="dropdown-item" href="#">
                        <i class="fa fa-comments"></i> Comments
                        <span class="badge badge-warning">42</span>
                      </a>
                      <div class="dropdown-header text-center">
                        <strong>Settings</strong>
                      </div>
                      <a class="dropdown-item" href="#">
                        <i class="fa fa-user"></i> Profile</a>
                      <a class="dropdown-item" href="#">
                        <i class="fa fa-wrench"></i> Settings</a>
                      <a class="dropdown-item" href="#">
                        <i class="fa fa-usd"></i> Payments
                        <span class="badge badge-secondary">42</span>
                      </a>
                      <a class="dropdown-item" href="#">
                        <i class="fa fa-file"></i> Projects
                        <span class="badge badge-primary">42</span>
                      </a>
                      <div class="divider"></div>
                      <a class="dropdown-item" href="#">
                        <i class="fa fa-shield"></i> Lock Account</a>
                      <a class="dropdown-item" href="#">
                        <i class="fa fa-lock"></i> Logout</a>
                    </div>
                  </li>
                </ul>

</header>