routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Auth::routes();
Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::resource('requirement', 'RequirementController')->middleware('auth');

Route::get('/requirement/{id}', 'RequirementController@show')->middleware('auth');
Route::resource('requirementtype','RequirementTypeController')->middleware('auth');
Route::get('/requirements/json', 'RequirementController@json')->middleware('auth');

/** 
 *   AUTH PROTECTED ROUTES
 */
Route::group(['middleware' => ['auth']], function()
{
    Route::get('/', function () {
        return view('dashboard');
    });
    Route::get('/requirements/search', 'RequirementController@search')->name('requirement.search');    
});

/**
 *  RESOURCES
 */
Route::resource('requirement', 'RequirementController',
                ['only' => ['index', 'show']])->middleware('auth');

Route::resource('requirement', 'RequirementController',
    ['except' => ['create', 'store', 'update', 'destroy']])->middleware(['auth']);

    Route::get('requirement/types', 'RequirementTypeController@index')->name('types.all');

    Route::prefix('requirement')->name('requirement.')->group(function () {
        Route::get('{id}/types', 'RequirementController@types')->name('types');
        Route::get('{id}/quotes', 'RequirementController@quotes')->name('quotes');
       
    });

    Route::prefix('requirements')->name('requirements.')->group(function () {

        Route::get('open', 'RequirementController@index')->name('open')->middleware(['auth']);
        Route::get('recent', 'RequirementController@getRecent')->name('recent')->middleware(['auth']);
        Route::get('quotes', 'RequirementController@getRecievedQuotes')->name('quotes')->middleware(['auth']);
        Route::get('{requirement}/show/json', 'RequirementController@getJson')->name('get.json')->middleware(['auth']);
       
    });

    /**
     *  QUOTE ROUTES
     */

    Route::prefix('quote')->name('quote.')->group(function () {

        Route::post('delete/{id}', 'QuoteController@delete')->name('delete')->middleware(['auth']);
        Route::get('/{id}', 'QuoteController@quotes')->name('show')->middleware(['auth']);
        Route::post('/sync','QuoteOptionController@sync')->name('sync')->middleware(['auth']);
        Route::get('/{requirementId}/new', 'QuoteController@create')->name('create')->middleware(['auth']);
        Route::post('/{requirementId}/store', 'QuoteController@store')->name('store')->middleware(['auth']);
        Route::post('submit/{requirementId}', 'QuoteController@submit')->name('submit')->middleware(['auth']);
        

        /**
         *  QUOTE OPTIONS
         */
        Route::get('/{requirementId}/options', 'QuoteOptionController@listByRequirement')->name('options')->middleware(['auth']);
        Route::post('/{requirementId}/options/{optionId}/delete', 'QuoteOptionController@destroy')->name('option.delete')->middleware(['auth']);
        Route::post('options/store', 'QuoteOptionController@store')->name('store')->middleware(['auth']);
    });

        
    /**
     *  JSON ROUTE PREFIX
     */
    
        Route::prefix('json/')->name('requirement.')->group(function () {

            /**
             *  Quote options
             */
            Route::post('quoteoption/{requirementId}/store', 'QuoteOptionController@store')->middleware(['auth']);
            Route::delete('quoteoption/{quoteoption}', 'QuoteOptionController@destroy')->middleware(['auth']);
            Route::post('quoteoption/{quoteOption}/update', 'QuoteOptionController@update')->middleware(['auth']);
           // Route::post('quoteoption/update/{quoteoption}', 'QuoteOptionController@update')->name('quoteoption.update')->middleware(['auth']);
        
            /**
             * 
             *  Quotes
             */
            Route::get('/quote/{requirement}', 'QuoteController@getQuoteByRequirement')->middleware(['auth']);
        });
    
    Route::prefix('quotes')->name('quotes.')->group(function () {

        Route::get('review', 'QuoteController@review')->name('review')->middleware(['auth']);
        Route::get('staged', 'QuoteController@getStaged')->name('staged')->middleware(['auth']);
        Route::get('review/confirmation', 'QuoteController@getConfirmation')->name('confirmation')->middleware(['auth']);
        
    
    });
    

    /**
     *  USER ROUTES
     */

    Route::prefix('user')->name('user.')->group(function () {

        Route::get('quotes', 'UserController@getQuotes')->name('quotes')->middleware(['auth']);
        Route::get('aircraft', 'UserController@getAircraft')->name('aircraft')->middleware(['auth']);
        Route::get('subscriptions','UserController@getSubscriptions')->name('subscriptions')->middleware(['auth']);
        Route::get('profile','UserController@getProfile')->name('profile')->middleware(['auth']);
        Route::get('dashboard', 'UserController@dashboard')->name('dashboard')->middleware(['auth']);
    });

app/Requirement.php
<?php

namespace App;
use App\Aircraft;
use App\RequirementType;
use Illuminate\Database\Eloquent\Model;
use Auth;

class Requirement extends Model
{

    protected $table = 'requirements';
    
   public function status(){
       return $this->belongsToMany('App\RequirementStatus');
   }

   public function types(){
    return $this->belongsToMany('App\RequirementType','requirement_requirementtypes', 'requirement_id', 'requirementtype_id');
   }

   public function aircraft(){
       return $this->belongsTo('App\Aircraft');
   }

   public function quotes(){
       return $this->hasMany('App\Quote');
   }

   public function getQuoteByUser($user)
   {
        foreach($this->quotes as $quote)
        {
            if ($quote->user_id == $user->id)
            {
                return $quote;
            }
        }
   }

}

app/RequirementType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class RequirementType extends Model
{
    protected $table = 'requirementtypes';
    public function requirements(){
        return $this->belongsToMany('App\Requirement', 'requirement_requirementtypes', 'requirement_id', 'requirementtype_id');
    }
}

app/Http/Controllers/RequirementController.php
<?php

namespace App\Http\Controllers;

use App\Requirement;
use App\RequirementType;
use Illuminate\Http\Request;
use Auth;
use Validator;
use Carbon\Carbon;
use App\Stats;

class RequirementController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index( $requirements = null )
    {


                $requirements = Requirement::where('status', '=', 'open')->with('aircraft')->get();


            return view('requirements.index.index')->with('requirements', $requirements);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Requirement  $requirement
     * @return \Illuminate\Http\Response
     */
    public function show(Requirement $requirement)
    {

        $types = $requirement->types;
        $quotes = $requirement->quotes->where('user_id', '==', Auth::user()->id);
        $hasQuoted = Auth::user()->hasQuoted($requirement);

        return view('requirements.single')
            ->with('requirement', $requirement)
            ->with('aircraft')
            ->with('hasQuoted', $hasQuoted)
            ->with('types', $types)
            ->with('quotes', $quotes);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Requirement  $requirement
     * @return \Illuminate\Http\Response
     */
    public function edit(Requirement $requirement)
    {
        $user = Auth::user();
        // return $requirement;
       return view('requirements.create-edit')
       ->with( 'requirement', $requirement)
       ->with('aircrafts', $user->aircrafts)
       ->with('activeTypes', $requirement->types);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Requirement  $requirement
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Requirement $requirement)
    {
        // if($request->requirementtypes){
        //     foreach($request->requirementtypes as $type){
        //         $requirement->requirement->type($type);
        //     }
        // }

        // $type = RequirementType::find(2);
        // $requirement->types()->save($type);
        $requirement->description = $request->description;
        $requirement->details = $request->details;
        $requirement->part_number = $request->part_number;
        $requirement->status = $request->status;
        $requirement->location = $request->location;
        $requirement->aircraft_id = $request->aircraft_id;
        $requirement->save();
        return $requirement;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Requirement  $requirement
     * @return \Illuminate\Http\Response
     */
    public function destroy(Requirement $requirement)
    {
        //
    }

    public function search(){
        return view('requirements.search');
    }

    public function json(){
        $requirements = Requirement::where('status', '=', 'open')->with('aircraft')->get();
        return $requirements;
    }

    public function types( $id ) {
        $requirement = Requirement::find($id);
        return $requirement->types;
    }

    public function getOpen(){
        $requirements = Requirement::where('status', '=', 'open')->with('aircraft')->get();
        return view('requirements.index.index')->with('requirements', $requirements);
    }

    public function getRecent(){

        $requirements = Requirement::where('status', '=', 'open')->
        where('created_at', '==', Carbon::now()->subDays(7))
        ->with('aircraft')->get();

        return view('requirements.index.index')->with('requirements', $requirements);
        
    }

    public function getRecievedQuotes( Request $request){

        $user = Auth::user();
        $quotes = collect();
        $userRequirements = $user->requirements;
        foreach( $userRequirements as $requirement){
            foreach( $requirement->quotes as $quote ){
                foreach( $quote->quoteOptions as $quoteOption)
                {
                    $quoteOption->quote->load('requirement');
                    $quoteOption->quote->requirement->aircraft = $quote->aircraft();
                    $quotes->push($quoteOption);
                }
            }
        }

        

        return view('requirements.recieved-quotes')->with('quotes', $quotes);
    }

    public function getJson( Requirement $requirement )
    {
        $requirement->quotes = $requirement->getQuoteByUser(Auth::user());
        return $requirement;
    }
}

resources/views/requirements/create-edit.blade.php
@extends('dashboard')

@section('dashboard-content')
<?php
    if ( Route::currentRouteName() == 'requirement.create' )
    { 
        $action = route('requirement.store');

    } else if ( Route::currentRouteName() == 'requirement.edit' ) {
        $action = route('requirement.update', $requirement);
    }
?>

<form v-on:submit.prevent="onSubmit" action={{ $action }} method="POST" id="requirement_form">
        @csrf
        <?php 

        // spoof route if it's an edit route.
        if ( Route::currentRouteName() == 'requirement.edit') { ?>
            @method('PUT')
        <?php } ?>

                
        <div class="form-group row">
                <label class="col-md-2 col-form-label"><strong>Aircraft</strong></label>
                <div class="col-md-10">

                        <select class="custom-select custom-select mb-3" v-model="requirement.aircraft_id">
                                <option v-for="aircraft in aircrafts" v-bind:value="aircraft.id">
                                  @{{ aircraft.tail_number }}
                                </option>
                              </select>
                </div>
             </div>

        <div class="form-group row">
            <label class="col-md-2 col-form-label"><strong>Part Number</strong></label>
            <div class="col-md-10">
                
                    <input name="part_number" class="form-control" type="text" v-model="requirement.part_number">
            </div>
        </div>
        
        <div class="form-group row">
                <label class="col-md-2 col-form-label"><strong>Description</strong></label>
                <div class="col-md-10">
                        <input name="description" class="form-control" type="text"  v-model="requirement.description">
                </div>
        </div>

        <div class="form-group row">
                <label class="col-md-2 col-form-label"><strong>Details</strong></label>
                <div class="col-md-10">
                        <textarea name="details" class="form-control" aria-label="With textarea" v-model="requirement.details">@{{ requirement.details }}</textarea>
                        <span class="form-text">Details of the requirement. Condition, sale type, terms, etc.</span>
                </div>
        </div>

        <div class="form-group row">
                <label class="col-md-2 col-form-label"><strong>Location</strong></label>
                <div class="col-md-10">
                        <input name="location" class="form-control" type="text" v-model="requirement.location">
                        <span class="form-text">Where will this need to be shipped? Airport, address, MRO facility, etc.</span>
                </div>
        </div>
<hr>
        <fieldset>

              
                <div class="form-group row">
                   <label class="col-md-2 col-form-label"><strong>Transaction Type</strong></label>
                   <div class="col-md-6">

                       <div v-for="type in types">
                        <div class="form-check form-check-inline">
                                
                                <label v-bind:for="type.id" class="switch switch-lg">                                   
                                    <input v-bind:id="type.id" @click="typeClick" class="form-check-input" type="checkbox" v-bind:checked="typeIsChecked(type)" v-bind:value="type.id" >
                                    <span></span>
                                    </label>
                                    <p>
                                    <label class="form-check-label" for="defaultCheck1"> <p style="margin-left:15px !important;">@{{ type.name}}<p></label></p>
                        </div>
                    </div>
                   </div>
                </div>
 
             </fieldset>

        <button id="submit" v-on:click="submit" class="btn btn-primary btn-lg" type="submit"><i class="fas fa-cloud"></i> Save</button>
    </form>

    <script>

            new Vue({
                el: '#jetbid_app',
                data: {
                  requirement: {!! json_encode($requirement) !!},
                  aircrafts: {!! json_encode($aircrafts) !!},
                  loading: false,
                  types: [],
                  checked: true
                },
                mounted() {
                    
                    this.requirement.types = {!! $activeTypes !!};

                    axios.get("{!! route('requirementtype.index') !!}",{ headers: 
                        { 'X-CSRF-TOKEN': '{!! csrf_token() !!}', }
                }).then( response => {
                    
                      this.types = response.data
                    });
                  },

                methods: {

                    typeIsChecked: function(type){

                        for ( var reqType in this.types ){
                            console.log(reqType);
                            if (reqType == type.id){
                               
                                return true;
                            }
                        }
                        return false;
                    },
                    typeClick: function(event){
                        console.log('yep');
                       
                    },
                    submit: function(event) {
                        this.loading = true;
                        if('{!! Route::currentRouteName() !!}' == 'requirement.edit'){
                            this.requirement._method = 'PUT';
                        }
                        axios.post('{!! $action !!}', this.requirement, 
                        { headers: 
                            { 'X-CSRF-TOKEN': '{!! csrf_token() !!}', }
                    }).then( function(response){
                        this.loading = false;
                        this.requirement = response;
                        swal("Saved", "", "success")
                
                    }).catch(error => {
                        
                        if (error ) {
                            console.log(error);
                          swal("Oh no!", error.message, "error");
                        } else {
                          swal.stopLoading();
                          swal.close();
                        }
                      });
                  }
                }
              })
            </script>
@endsection

resources/views/requirements/quote-approval-confirmation.blade.php
@extends('dashboard')

@section('dashboard-content')

{{ dump($quotes )}}

@endsection

@section('dashboard-right-sidebar')

@endsection

resources/views/requirements/quote-approval-wizard.blade.php
@extends('dashboard')

@section('dashboard-content')

    <div id="wizard">

       <div class="card" v-for="quote in quotes">
        <div class="card-header bg-custom card-header-primary">
            <div class="float-right btn-group">
                    <button @click="declineQuote(quote)" class="btn btn-outline-light btn-sm">Decline</button>
                    <button @click="removeQuote(quote)" class="btn btn-outline-light btn-sm">Remove</button>
            </div>
           
        </div>
        <div class="card-body">
                <nav>
                        <div class="nav nav-tabs" id="nav-tab" role="tablist">
                          <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Quote</a>
                          <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false"> <i class="fas fa-info-circle"></i> Terms</a>
                      
                        </div>
                      </nav>
                      <div class="tab-content" id="nav-tabContent">
                        <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
                                <div class="row">
                                        <dt class="col-sm-3">Part Number</dt>
                                        <dd class="col-sm-9">@{{ quote.requirement.part_number }}</dd>
                    
                                        <dt class="col-sm-3">Description</dt>
                                        <dd class="col-sm-9">@{{ quote.description }}</dd>
                    
                                        <dt v-if="quote.lead_time" class="col-sm-3">Lead Time</dt>
                                        <dd v-if="quote.lead_time" class="col-sm-9">@{{ quote.lead_time }}</dd>
                    
                                        <dt class="col-sm-3">Price</dt>
                                        <dd class="col-sm-9">@{{ quote.price }}</dd>
                    
                    
                                        <dt class="col-sm-3">Vendor</dt>
                                        <dd class="col-sm-9">
                                            
                                            <ul class="list-unstyled">
                                                <li><i class="fas fa-user-circle"></i> user here</li>
                                                <li><i class="fas fa-user-circle"></i> Flight Motion</li>
                                                <li><i class="fas fa-envelope-square"></i> <a href="mailto:">asdf</a></li>
                                            </ul>
                                        </dd>
                          
                                </div>
                        </div>
                        <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
                            Terms and conditions here
                        </div>
                      </div>


<hr>
        <div class="row">

        <div class="col-sm-4">
                <div class="form-group">
                    <label>Ship to:</label>
                    <select class="form-control">
                        <option v-for="address in userOptions.shipping.addresses" v-bind:selected="address.default">@{{ address.label }}</option>
                    </select>
                </div>
            </div>
            <div class="col-sm-4">
                    <div class="form-group">
                        <label>Shipping Carrier</label>
                        <select class="form-control">
                
                            <option v-for="carrier in userOptions.shipping.carriers" v-bind:selected="carrier.default"> @{{carrier.label}} - @{{ carrier.account_number }} - @{{ carrier.rate }}</option>
                        </select>
                    </div>
                </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label>Shipping Rate</label>
                   <input class="form-control">
                </div>
            </div>
        </div>
        <div class="row">
                <div class="col-sm-12">
                    
                        <div  v-for="term in userOptions.terms" v-if="term.type == 'purchase'" class="form-group">
                            <label>Purchase Terms</label>
                        
                        <textarea class="form-control" rows="4" >@{{ term.content }}</textarea>

                    </div>
                </div>
        </div>

        </div>
       </div>
    </div>

@endsection

@section('dashboard-right-sidebar')
<div class="card">
    <div class="card-body">
        <a href="{{ route('quotes.confirmation') }}" class="btn btn-block btn-primary btn-lg">Submit</a>
    </div>
</div>
@endsection

@section('footer-scripts')

<script>

    var wizard = new Vue({
        el: '#wizard',
        data: {
            quotes: [],
            quoteSync: false,
            userOptions: {!! $user->options !!},
            selected: [],
        },
        mounted(){
            this.getStagedQuotes();
        },
        methods: {

            getCarrierRate: function(carrier)
            {

            },

            getStagedQuotes: function(){
                var vm = this;
                axios.get('{!! route("quotes.staged") !!}', { headers:  { 'X-CSRF-TOKEN': '{!! csrf_token() !!}', }})
                .then( function(response){
                  vm.quotes = response.data;
                  vm.quoteSync = false;
              }).catch(error => {
                  if (error ) {
                      console.log(error);
                  } 
                });
              },

            removeQuote(quote)
            {
                vm = this;
                var index = vm.quotes.indexOf(quote);
                vm.quotes.splice(index, 1);
                vm.syncQuotes();
                vm.getStagedQuotes();

            },

            declineQuote(quote)
            {
                swal("Are you sure you want to decline this quote?", {
                    buttons: ["Oops!", "Yes, decline this quote."],
                  });
                
                  quote.status = 'declined';
                 quote.confirmed = true;
                  this.removeQuote(quote);

            },

                      // sync the quotes.
      syncQuotes: function(){
        var vm = this;
        axios.post('{!! route("quote.sync") !!}', vm.quotes, 
          { headers: 
            { 'X-CSRF-TOKEN': '{!! csrf_token() !!}', }
        }).then( function( response ){
          
    }).catch(error => {
        if ( error ) {
            console.log(error);
        } 
      });

    }
        }
    });

</script>
<style>
.bg-custom {
    background: #8360c3;  /* fallback for old browsers */
background: -webkit-linear-gradient(to left, #2ebf91, #8360c3);  /* Chrome 10-25, Safari 5.1-6 */
background: linear-gradient(to left, #2ebf91, #8360c3); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
color: #fff !important;

}
</style>
@endsection

resources/views/requirements/requirement-form.blade.php
<?php
    if ( Route::currentRouteName() == 'requirement.create' )
    { 
        $action = route('requirement.store');
    } else if ( Route::currentRouteName() == 'requirement.edit' ) {
        $action = route('requirement.update')
    }
?>

<form action={{ $action }} method="POST">
        @csrf
        @if($action == route('requirement.edit') )
        @method('PUT')
        @endif
        <div class="col-md-10">
                <input class="form-control" type="text" value="{{ $requirement->part_number or '' }}">
                <span class="form-text">A block of help text that breaks onto a new line and may extend beyond one line.</span>
        </div>
        <button class="btn btn-primary" type="submit">Submit form</button>
    </form>